### ISSUE TITLE
pac0.bin file offset/file size

### ISSUE THREAD

**Issue by ghost** [marco-calautti/FF4Tools#3]
@marco-calautti 
Does the ff4tools also update the pac0.bin file when it is executed? pac0.bin stores the file offsets of files inside pac1.bin is that right? I'm wondering so because I've been replacing the .at3 sound files and their file sizes have increased/decreased.

I can play the new tracks perfectly in the game's music player, but whenever it's triggered/called during gameplay event, I get crashes, an illegal read error. I'm narrowing it down to pac0.bin file offset issue. So far the game is only crashing with some of the newer at3 files and I'm wondering if the offsets for the at3 files are not updated in pac0.bin, resulting in the illegal read error and freeze.

**Comment by marco-calautti** [comment]
Unless there is some bug in my code the offsets of all files together with their size are updated.

**Comment by marco-calautti** [comment]
If the file size is really the problem, then i would verify that by changing the at3 files with some other sound which is smaller, pad the remaining space to get the original file size and rebuild the archive. In this way, the file sizes are the same, and if the game crashes anyway, then the issue is something else.

EDIT
Can you tell me which files cause problems, their original size and the size of the new files?

**Comment by ghost** [comment]
> Unless there is some bug in my code the offsets of all files together with their size are updated.

Ah I was just inspecting the two pac0.bin. *(the original unedited and after updated).* They appear to have been updated at offset `0x138`. (changed from `C4` in the original, to `00` after repack) I compared the two via hex editor file-compare and saw the two differences there.

> If the file size is really the problem, then i would verify that by changing the at3 files with some other sound which is smaller, pad the remaining space to get the original file size and rebuild the archive. In this way, the file sizes are the same, and if the game crashes anyway, then the issue is something else.
> 
> EDIT Can you tell me which files cause problems, their original size and the size of the new files?

Currently BGM_AIRSHIP.at3 (from directory: `sound\BGM_AIRSHIP.at3` has the issue.

Original file size:
`BGM_AIRSHIP.at3 — 267,504 bytes (261 KB)`

New at3 file size:
`BGM_AIRSHIP.at3 — 2,872,748 bytes (2.73 MB)`

I can play the new audio in the game's music player perfectly, loops and everything, however, when it's time to hear it during gameplay—the moment you get on the Falcon airship, the game crashes.

Thing is, almost all of the other new at3 I've replaced are also bigger than the original and they play fine in game with no crashes.
It's just some of them in few cases.

If it is the file size problem, then that would mean the same thing happens when I tried to use a bigger resolution .tm2 texture.
Doing that did increase the .lzs archive a bit and two instances occurred:

The first bigger texture I tested was the numeric damage points tm2 image (i.e. the numbers when you do damage to enemy/do healing, get attacked/hit, etc).
The game didn't crash, it just didn't display the texture anymore (no numbers showed).

The second instance was bigger texture size the character's sprite sheets (increase by x2, integer); that resulted in a crash immediately when loaded. (entering a battle, etc.)

Could also be a file size problem to like the at3.

**Comment by marco-calautti** [comment]
I personally used the archiver for a fan translation and a large number of files got bigger in the process and I had no issues whatsoever. I think the problem here is only loosely related to size. First, you are making an at3 file increase from 300kb to more than 2mbs. I would not be surprised if the game simply does not have enough memory for playing it, during gameplay (or the at3 has different bitrate, that the games simply does not expect). Similarly, you cannot expect to change the resolution of a texture and the game to be able to adapt seamlessly. The game expects that texture to have a certain resolution, and changing it very likely will make it crash.

**Comment by ghost** [comment]
> I personally used the archiver for a fan translation and a large number of files got bigger in the process and I had no issues whatsoever. I think the problem here is only loosely related to size. First, you are making an at3 file increase from 300kb to more than 2mbs. I would not be surprised if the game simply does not have enough memory for playing it, during gameplay (or the at3 has different bitrate, that the games simply does not expect). Similarly, you cannot expect to change the resolution of a texture and the game to be able to adapt seamlessly. The game expects that texture to have a certain resolution, and changing it very likely will make it crash.

Oh yeah, when I tried to open the message.lzs the tool gave an error:

`Record index 0 mismatch!`

and nothing came out of it.
It can add text too?

This is the command I used:

`FF4MiniArchiver -extract message_en.lzs message_en`

This is why I'm looking to remove the limitations it has on bigger at3 files, but again, it didn't make sense for this one file to have that issue when I have even bigger at3 files and they play perfectly with loop in game no crashes. If that memory was really an issue, wouldn't it be the same for the rest of the bigger at3? I also can't check the bit rate of the at3, but I'm guessing the at3 tool gives it all the same bitrate.
EDIT: I just tested BGM_AIRSHIP from the After Years side and it plays absolutely perfectly, no crashes nothing.
I think it may be a save game thing again, either that or... I don't know. But it does work in both circumstances. The game's music player and in the After Years side.

Regarding the texture, I heard this could be due to the game's handling of VRAM overflow, could that possibly be? Narrowing done the root cause.

**Comment by marco-calautti** [comment]
I would suggest better reading how to use the archiver. This is a tool only intended to extract and rebuild the PAC archive, and nothing else. You cannot expect it to work lzs files, like the message_en.lz. For that file you would need some other tool. At the time of the fan translation I worked on, I created a couple of scripts for [Cartographer](http://www.romhacking.net/utilities/647/) and [Atlas](http://www.romhacking.net/utilities/224/), which are general purpose tools for extracting and reinserting text in files.

I might upload these scripts to this repository once I find the time. In the meanwhile, I would suggest clarifying what is the real issue with your files. Have you tried recreating the archive by changing *only* the at3 that is causing problems? Do you still have issues when doing this?.

The fact that other files work fine even when expanded does not mean much, as this always depend on the amount of RAM available by the game overall, when executing a certain scene. Do not forget the PSP only has 32MB of RAM.
If it were an issues with how the archive is rebuilt, then I would expect the file to be inaccesible also in the music player.
The problem must have more likely to do on how the game handles this file, and it actually expects from it.

**Comment by marco-calautti** [comment]
Have you also checked that you are recreating the at3 with the same specs as the original one? I see the original has 41000 sample rate, and 64 kbs bit rate.

**Comment by ghost** [comment]
> I would suggest better reading how to use the archiver. This is a tool only intended to extract and rebuild the PAC archive, and nothing else. You cannot expect it to work lzs files, like the message_en.lz.

I did read how to use the archiver, thus this far. I've been using that same FF4Miniarchiver to replace .tm2 inside the lzs archive.
Looks like it can do more than only rebuild the PAC archive, since it handled the lzs archive to get the tile sets and .cn2 files and script, that's why I figured it could also handle the message_xx.lzs.

> I would suggest clarifying what is the real issue with your files. Have you tried recreating the archive by changing _only_ the at3 that is causing problems? Do you still have issues when doing this?.

The usage of bigger tm2 resolution images.
I have tested changing only the BGM_AIRSHIP.at3, same thing. But it only happens in the original FF4 after loading a save, not the After Years, nor the music player. Why is that? Couldn't be the file itself if it works in more than one instance.
And the usage of bigger tm2 resolution images.

> The fact that other files work fine even when expanded does not mean much, as this always depend on the amount of RAM available by the game overall, when executing a certain scene. Do not forget the PSP only has 32MB of RAM. If it were an issues with how the archive is rebuilt, then I would expect the file to be inaccesible also in the music player. The problem must have more likely to do on how the game handles this file, and it actually expects from it.

How do I increase that amount of RAM? I've had a different custom at3 for this same file and it worked perfectly.
If RAM is really that problematic, that should be changed for the sake of the at3 and textures too.

**Comment by marco-calautti** [comment]
I tried replacing the BGM_AIRSHIP.at3 file with a larger one (1.6 MB), and the game does not crash (actually it does not reproduce it but I guess this has to do with the sampling rate that I am forced to set to 48000 hz with the current tools I have. So, the crash you get seems to not be related to an issue with my archiver, but on how large and the actual format you use for the file.

Regarding the lzs files. This github repo hosts more than one tool. I thought your were talking about the ff4achiver. There are 4 tools:
ff4archiver deals with the big PAC archive
ff4miniarchiver deals with the small lzs archives (not all lzs files are archives in this format)
ff4monstersorter sorts the monsters in the bestiary according to their names in the message_en.lzs. This is needed if you change the names of the monsters, and you want them displayed sorted by their new name, rather than the original ones.
ff4decompressor is usually not used on its own, and it used to compress and decompress files using the games compression algorithm.

message_en.lzs etc is its own format that no tools in this repo supports.

Regarding RAM, you simply can't. The RAM is the memory the actual PSP hardware has available. The only thing you can do is to try to reduce the size of your at3 file to make it fit in the memory the game has available.
Similarly, as you suggested, if you increase the resolution of textures, these will occupy more space in video memory, and thus will very likely overwrite other graphics, and break the game.

**Comment by marco-calautti** [comment]
I tried replacing the BGM_AIRSHIP.at3 with another file from the game that is slightly larger, and everything works. When replacing it with a much larger file, the issue occurs. I tried re-extracting the new archive, and the new large file is perfectly extracted. So, I can confirm my archive works as intended. You simply cannot use too large files with this game.

**Comment by ghost** [comment]
> Regarding the lzs files. This github repo hosts more than one tool. I thought your were talking about the ff4achiver. There are 4 tools: ff4archiver deals with the big PAC archive ff4miniarchiver deals with the small lzs archives (not all lzs files are archives in this format) ff4monstersorter sorts the monsters in the bestiary according to their names in the message_en.lzs. This is needed if you change the names of the monsters, and you want them displayed sorted by their new name, rather than the original ones. ff4decompressor is usually not used on its own, and it used to compress and decompress files using the games compression algorithm.
> 
The name of the monsters are in `message_xx.lzs` right, or other location?

> message_en.lzs etc is its own format that no tools in this repo supports.
> 

Alright good to know, I put that into what needs to be created.

> Regarding RAM, you simply can't. The RAM is the memory the actual PSP hardware has available.

There has to be way to increase that ram since its on PC. Either by rebuilding the emulator? Or the brute force, maybe not 100% accurate but more doable method: reverse and porting like opentomb. That will be lifted and for extra data to be reserved for other things!

>The only thing you can do is to try to reduce the size of your at3 file to make it fit in the memory the game has available. Similarly, as you suggested, if you increase the resolution of textures, these will occupy more space in video memory, and thus will very likely overwrite other graphics, and break the game.

Sure, I could, but since I've grown accustom to using beautiful 2k textures I've (temporarily) replaced via emulator's texture-replace feature, and redone spell effects, I _must_ have that removed so it can be done permanently. _Where there's gil, there's a way._

I'd offer you to join us in this endeavor, maybe even earn something, but it appears you've retired since the last tool update?
The more the merrier; the better.

**Comment by ghost** [comment]
The at3 only occurs during gameplay of og ff4. it never happens during the after years.
have you tested your at3 in the after years? It's strange how the after years has no problem playing every at3 yet the original ff4 does.

**Comment by marco-calautti** [comment]
The fact that the other games are able to load the at3 file is another indication that the issue is not with the archive, but on how the og ff4 game handles audio files. There is not much I can do here to help. You should reverse engineer the game and understand what happens when it loads that audio file. If you are not able to do that, then the only thing I can suggest is to try different files size to find out what is the maximim og ff4 can handle, and then try to compromise on that using a lower bitrate.

Regarding texture replacement via emulators: well this is a completely different story. If you want to do that, the emulator must support this feature. In this case, you usually do not even need to change the game ISO at all. The emulator should have a setting where you ask it to dump all textures while the game is running. Then, you simply replace these textures on your harddrive, and the emulator will pick them up and replace them on the fly.

**Comment by ghost** [comment]
> You should reverse engineer the game and understand what happens when it loads that audio file.

That's exactly what is undergone right now. og ff4 needs a lot of its old limits raised lifted and removed.

> Regarding texture replacement via emulators: well this is a completely different story. If you want to do that, the emulator must support this feature. In this case, you usually do not even need to change the game ISO at all. The emulator should have a setting where you ask it to dump all textures while the game is running. Then, you simply replace these textures on your harddrive, and the emulator will pick them up and replace them on the fly.

I've already been doing that via PPSSPP. It's how I've been able to test things so far. But now it's time to make those assets permanent, since replacing textures internally causes the image hashes on texture replacement dump in PPSSPP to change.

I am glad we were able to narrow done this issue to what I had theorized, so that we now know in my initial OT post that it is not the pac archive at fault here.
